#pragma once

#define DIODE_DIRECTION COL2ROW
#define MATRIX_ROWS 8
#define MATRIX_COLS 6

#define EE_HANDS
#define SPLIT_USB_DETECT
#define USE_SERIAL
#define MASTER_LEFT
#define SOFT_SERIAL_PIN GP0

#define MATRIX_ROW_PINS { GP9, GP10, GP11, GP12 }
#define MATRIX_COL_PINS { GP29, GP28, GP27, GP26, GP15, GP7 }

#define MATRIX_ROW_PINS_RIGHT { GP10, GP11, GP12, GP13 }
#define MATRIX_COL_PINS_RIGHT { GP29, GP28, GP27, GP26, GP15, GP14 }

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define TAPPING_TERM 190
