#pragma once

#define DIODE_DIRECTION COL2ROW
#define MATRIX_ROWS 8
#define MATRIX_COLS 6

#define EE_HANDS
#define SPLIT_USB_DETECT
#define USE_SERIAL
#define MASTER_LEFT
#define SOFT_SERIAL_PIN GP0

#define MATRIX_ROW_PINS { GP10, GP11, GP12, GP13 }
#define MATRIX_COL_PINS { GP8, GP7, GP6, GP5, GP4, GP3 }

#define MATRIX_ROW_PINS_RIGHT { GP13, GP12, GP11, GP10 }
#define MATRIX_COL_PINS_RIGHT { GP8, GP7, GP6, GP4, GP5, GP3 }

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define TAPPING_TERM 190
